# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-webapp
  template:
    metadata:
      labels:
        app: todolist-webapp
    spec:
      containers:
      - name: todolist-webapp
        image: tnoone125/todolist_webapp:latest
        ports:
        - containerPort: 5000