apiVersion: v1  # Specifies the API version for Service
kind: Service
metadata:
  name: todolist-webapp
spec:
  selector:
    app: todolist-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer